### ISSUE TITLE
Have you seen ebiten's purego project? You might be able to simplify your project with that <3

### ISSUE THREAD

**Issue by shehackedyou** [bloeys/nmage#3]

**Comment by shehackedyou** [comment]
since you stream to others, might want to know this information so you can share using purego to take out CGO from game engines

**Comment by bloeys** [comment]
That's actually super cool, thanks for sharing!

I'll definitely keep it on my radar because simplifying the build would be great. However, not sure how practical doing it is, since nMage currently uses go wrappers of SDL2, OpenGL, and Dear ImGui, which would mean those wrapper projects need to use purego as well for the build to not require C :/

Thanks for the headsup though, will keep it in mind and see if an opportunity comes up to move to it fully.

**Comment by bloeys** [comment]
Thanks for the suggestion, added to backlog. Closing.
